### ISSUE TITLE
AccountInfoQuery panics on nil ProxyAccountID on testnet release today

### ISSUE THREAD

**Issue by sam-at-luther** [hashgraph/hedera-sdk-go#121]
Earlier today testnet was upgraded and we are seeing a new panic in AccountInfoQuery:

```go
package main

import (
	"os"

	hedera "github.com/hashgraph/hedera-sdk-go/v2"
)

func main() {
	htsClient := hedera.ClientForTestnet()
	operatorAccountID, err := hedera.AccountIDFromString(os.Getenv("JUNO_ORACLE_HTS_OPERATOR_ID"))
	if err != nil {
		panic(err)
	}

	operatorKey, err := hedera.PrivateKeyFromString(os.Getenv("JUNO_ORACLE_HTS_OPERATOR_KEY_SECRET"))
	if err != nil {
		panic(err)
	}

	htsClient.SetOperator(operatorAccountID, operatorKey)

	nodeID := "0.0.3"
	accountID := "0.0.377961"

	nodeAccountID, err := hedera.AccountIDFromString(nodeID)
	if err != nil {
		panic(err)
	}

	investorAccountID, err := hedera.AccountIDFromString(accountID)
	if err != nil {
		panic(err)
	}

	hedera.NewAccountInfoQuery().
		SetAccountID(investorAccountID).
		SetNodeAccountIDs([]hedera.AccountID{nodeAccountID}).
		Execute(htsClient)

	// THE ABOVE CALL PANICS ON v2.1.2
	/*
		panic: runtime error: invalid memory address or nil pointer dereference
		[signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0x14bb217]

		goroutine 1 [running]:
		github.com/hashgraph/hedera-sdk-go/v2.accountIDFromProtobuf(...)
		        /Users/swood/work/pkg/mod/github.com/hashgraph/hedera-sdk-go/v2@v2.1.2/account_id.go:82
		github.com/hashgraph/hedera-sdk-go/v2.accountInfoFromProtobuf(0xc00016c000, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
		        /Users/swood/work/pkg/mod/github.com/hashgraph/hedera-sdk-go/v2@v2.1.2/account_info.go:47 +0x277
		github.com/hashgraph/hedera-sdk-go/v2.(*AccountInfoQuery).Execute(0xc0001c91e0, 0xc0001a66e0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
		        /Users/swood/work/pkg/mod/github.com/hashgraph/hedera-sdk-go/v2@v2.1.2/account_info_query.go:170 +0x313
		main.main()
		        /Users/swood/work/src/bitbucket.org/luthersystems/juno/oracleserv/oracle/hts/bug/bug.go:39 +0x3ca
	*/
}
```

**Comment by sam-at-luther** [comment]
I bumped to v2.1.4 and still see the panic:
```go
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0x14daf47]

goroutine 1 [running]:
github.com/hashgraph/hedera-sdk-go/v2.accountIDFromProtobuf(...)
        /Users/swood/work/pkg/mod/github.com/hashgraph/hedera-sdk-go/v2@v2.1.4/account_id.go:83
github.com/hashgraph/hedera-sdk-go/v2.accountInfoFromProtobuf(0xc0001701a0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /Users/swood/work/pkg/mod/github.com/hashgraph/hedera-sdk-go/v2@v2.1.4/account_info.go:46 +0x277
github.com/hashgraph/hedera-sdk-go/v2.(*AccountInfoQuery).Execute(0xc0001433f0, 0xc00010a730, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /Users/swood/work/pkg/mod/github.com/hashgraph/hedera-sdk-go/v2@v2.1.4/account_info_query.go:173 +0x21c
main.main()
        /Users/swood/work/src/bitbucket.org/luthersystems/juno/oracleserv/oracle/hts/bug/bug.go:39 +0x3ca
```
