### ISSUE TITLE
transaction_receipt.go:54 nil pointer panic

### ISSUE THREAD

**Issue by tomzhenghedera** [hashgraph/hedera-sdk-go#177]
I happened to get this panic sometime, especially while network is on load:

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x30 pc=0x93f2e5]
goroutine 1 [running]:
github.com/hashgraph/hedera-sdk-go/v2.transactionReceiptFromProtobuf(0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /home/tzheng/go/pkg/mod/github.com/hashgraph/hedera-sdk-go/v2@v2.1.5/transaction_receipt.go:54 +0x65
github.com/hashgraph/hedera-sdk-go/v2.(*TransactionReceiptQuery).Execute(0xc00065c3f0, 0xc0000aa7d0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /home/tzheng/go/pkg/mod/github.com/hashgraph/hedera-sdk-go/v2@v2.1.5/transaction_receipt_query.go:163 +0x2a0
github.com/hashgraph/hedera-sdk-go/v2.TransactionResponse.GetReceipt(0xc00064c560, 0xc0007006e0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x12, 0xc0009add40, ...)
        /home/tzheng/go/pkg/mod/github.com/hashgraph/hedera-sdk-go/v2@v2.1.5/transaction_response.go:14 +0x1b1
```

Looks to me there needs a null pointer check here

```
52 func transactionReceiptFromProtobuf(protoReceipt *proto.TransactionReceipt) Transactio    nReceipt {
 53     var accountID *AccountID
 54     if protoReceipt.AccountID != nil {
 55         accountIDValue := accountIDFromProtobuf(protoReceipt.AccountID)
 56         accountID = &accountIDValue
 57     }
```
this is from `go/v2@v2.1.5/transaction_receipt.go:54`

**Comment by danielakhterov** [comment]
I believe this has already been resolved in `v2.1.7` since we have a `nil` check at the beginning now.
```go
func transactionReceiptFromProtobuf(protoReceipt *proto.TransactionReceipt) TransactionReceipt {
	if protoReceipt == nil {
		return TransactionReceipt{}
	}
	var accountID *AccountID
	if protoReceipt.AccountID != nil {
		accountIDValue := accountIDFromProtobuf(protoReceipt.AccountID)
		accountID = &accountIDValue
	}

```
