### ISSUE TITLE
InvalidProtocolBufferException when executing signed transaction (golang) on Java server

### ISSUE THREAD

**Issue by robkainz** [hashgraph/hedera-sdk-go#301]
### Description

There seems to some kind of incompatibility between the Go and Java Hedera SDKs and their use of Google's protobuf libraries and this is currently blocking us on our WW HTS release due to a last-minute, but important, feature. I generate a transaction on our server (Java), have the client sign it (golang) and send it back to the server signed for execution (so the server pays all fees.) Unfortunately, when run on the server I get this error:
  
2021-10-25 08:14:22,957 ERROR | http-nio-8080-exec-2 | o.a.c.c.C.[Tomcat].[localhost].[/].[dispatcherServlet]  | Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception 
com.google.protobuf.InvalidProtocolBufferException: Protocol message contained an invalid tag (zero).
	at com.google.protobuf.InvalidProtocolBufferException.invalidTag(InvalidProtocolBufferException.java:125)
	at com.google.protobuf.ArrayDecoders.decodeUnknownField(ArrayDecoders.java:1036)
	at com.google.protobuf.ArrayDecoders.decodeUnknownField(ArrayDecoders.java:1028)
	at com.google.protobuf.MessageSchema.parseProto3Message(MessageSchema.java:5426)
	at com.google.protobuf.MessageSchema.mergeFrom(MessageSchema.java:5442)
	at com.google.protobuf.GeneratedMessageLite.parsePartialFrom(GeneratedMessageLite.java:1567)
	at com.google.protobuf.GeneratedMessageLite.parseFrom(GeneratedMessageLite.java:1671)
	at com.hedera.hashgraph.sdk.proto.TransactionList.parseFrom(TransactionList.java:148)
	at com.hedera.hashgraph.sdk.Transaction.fromBytes(Transaction.java:149)
	at 
...

### Steps to reproduce

1. Create a token association transaction in Java - get the bytes (I convert them to a hex string to pass back to the golang client)
2. Have the golang client sign the transaction and return the updated signed bytes to the server
3. Execute the transaction on the server

### Hedera network

testnet

### Version

v2.3.0

### Operating system

macOS

**Comment by danielakhterov** [comment]
I think I see the issue.
```
	switch newTx := transaction.(type) {
	case hedera.TokenAssociateTransaction:
		signedTransaction, err = privKey.SignTransaction(&newTx.Transaction)
	}
	if err!=nil {
		return "", err
	}

	return hex.EncodeToString(signedTransaction), nil
```
Specifically `signedTransaction, err = privKey.SignTransaction(...)`. This does not return a signed transaction, but instead returns the signature. The transaction that is signed will still be `newTx` so I recommend changing `hex.EncodeToString(signedTransaction), nil` to `hex.EncodeToString(newTx.ToBytes())`

**Comment by robkainz** [comment]
Thank you so much Daniel, you were correct. Your code suggestion isn't fully correct, but it was easy to get it working from there. I'm sorry I missed that, it should have been obvious to me. I now have our airdrop feature fully working!

**Comment by danielakhterov** [comment]
I'm glad to hear that everything worked out, and no worries about missing that it happens to the best of us.
