### ISSUE TITLE
getReceipt occasionally returns Invalid node AccountID was set for transaction: 0.0.0 (v2.5.1)

### ISSUE THREAD

**Issue by failfmi** [hashgraph/hedera-sdk-go#344]
### Description

Submitting a TransferTransaction (on testnet) and getting a receipt for the transaction occasionally throws a Invalid node AccountID was set for transaction: 0.0.0 error.

Similar to #292 , but as described, it now occurs on `v2.5.1`.

### Steps to reproduce

```
panic: cannot set node account ID of 0.0.0
| goroutine 143 [running]:
| github.com/hashgraph/hedera-sdk-go/v2.(*Query).SetNodeAccountIDs(0xc0002c6e70, 0xc000685b60, 0x1, 0x1, 0x0)
| 	/go/pkg/mod/github.com/hashgraph/hedera-sdk-go/v2@v2.5.1/query.go:48 +0xcc
| github.com/hashgraph/hedera-sdk-go/v2.(*TransactionReceiptQuery).SetNodeAccountIDs(...)
| 	/go/pkg/mod/github.com/hashgraph/hedera-sdk-go/v2@v2.5.1/transaction_receipt_query.go:162
| github.com/hashgraph/hedera-sdk-go/v2.TransactionResponse.GetReceipt(0xc0003eaac0, 0xc0003eab00, 0x0, 0xc0003eaac0, 0xc0003eab00, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
| 	/go/pkg/mod/github.com/hashgraph/hedera-sdk-go/v2@v2.5.1/transaction_response.go:13 +0x1cf
```

### Additional context

No response

### Hedera network

testnet

### Version

v2.5.1

### Operating system

Linux

**Comment by danielakhterov** [comment]
Resolved in v2.6.0
