### ISSUE TITLE
[sdk-go-2.7.0-beta.1] ECDSA key: panic: libsecp256k1 error

### ISSUE THREAD

**Issue by tomzhenghedera** [hashgraph/hedera-sdk-go#359]
### Description

Running `sdk-go-2.7.0-beta.1` with a ECDSA key saw

```
panic: libsecp256k1 error

goroutine 1 [running]:
github.com/ethereum/go-ethereum/crypto/secp256k1.CompressPubkey(0xc00012d440, 0xa6353c)
        /home/tzheng/go/pkg/mod/github.com/ethereum/go-ethereum@v1.10.13/crypto/secp256k1/secp256.go:166 +0x97
github.com/ethereum/go-ethereum/crypto.CompressPubkey(...)
        /home/tzheng/go/pkg/mod/github.com/ethereum/go-ethereum@v1.10.13/crypto/signature_cgo.go:82
github.com/hashgraph/hedera-sdk-go/v2._ECDSAPublicKey._BytesRaw(...)
        /home/tzheng/go/pkg/mod/github.com/hashgraph/hedera-sdk-go/v2@v2.7.0-beta.1/ecdsa_public_key.go:84
github.com/hashgraph/hedera-sdk-go/v2._ECDSAPublicKey._BytesDer({0x20000c0001d3398})
        /home/tzheng/go/pkg/mod/github.com/hashgraph/hedera-sdk-go/v2@v2.7.0-beta.1/ecdsa_public_key.go:89 +0x6d
github.com/hashgraph/hedera-sdk-go/v2._ECDSAPublicKey._StringDer({0x16})
        /home/tzheng/go/pkg/mod/github.com/hashgraph/hedera-sdk-go/v2@v2.7.0-beta.1/ecdsa_public_key.go:96 +0x19
github.com/hashgraph/hedera-sdk-go/v2.PublicKey.String({0xc00012e548, 0x0})
        /home/tzheng/go/pkg/mod/github.com/hashgraph/hedera-sdk-go/v2@v2.7.0-beta.1/crypto.go:492 +0x5d
github.com/hashgraph/hedera-sdk-go/v2.(*Transaction)._KeyAlreadySigned(0x576978, {0x0, 0xc0001267e0})
        /home/tzheng/go/pkg/mod/github.com/hashgraph/hedera-sdk-go/v2@v2.7.0-beta.1/transaction.go:395 +0x79
github.com/hashgraph/hedera-sdk-go/v2.(*TokenAssociateTransaction).SignWith(0xc00014da40, {0x0, 0xc0001267e0}, 0xc0001267f8)
        /home/tzheng/go/pkg/mod/github.com/hashgraph/hedera-sdk-go/v2@v2.7.0-beta.1/token_associate_transaction.go:228 +0x3d
github.com/hashgraph/hedera-sdk-go/v2.(*TokenAssociateTransaction).Execute(0xc00014da40, 0xc0001c8500)
        /home/tzheng/go/pkg/mod/github.com/hashgraph/hedera-sdk-go/v2@v2.7.0-beta.1/token_associate_transaction.go:257 +0x28f
```

### Steps to reproduce

1.  key, err := hedera.PrivateKeyFromStringECSDA("3030020100300706052b8104000a04220420d790c27a81d745ad3340e27dacedc982d1f9252c0d7a4582da9847e2094603d4")
2.  fmt.Printf("public key = %s\n", key.PublicKey().String())

### Hedera network

other

### Version

2.7.0-beta.1

### Operating system

Linux

**Comment by SimiHunjan** [comment]
fixed v2.7.0
