### ISSUE TITLE
Exception occurs when querying account balance

### ISSUE THREAD

**Issue by JeremyPansier** [hashgraph/hedera-sdk-go#852]
### Description

Following the tutorial for [creating an account](https://docs.hedera.com/hedera/getting-started/create-an-account), running exactly the same code, an exception occurs when querying the account balance.

The issue is present in version v2.34.0 and was not observed in v2.33.0.

### Steps to reproduce

1. Follow the tutorial for [creating an account](https://docs.hedera.com/hedera/getting-started/create-an-account)
2. Run the program

### Expected behaviour
As described in the tutorial ([sample output](https://docs.hedera.com/hedera/getting-started/create-an-account#sample-output)), after running the program, the output should be:
```
New account ID: 0.0.13724748
New account balance: 1000 tinybars.
```

### Actual behaviour
After running the program, the output is:
```
New account ID: 0.0.7491771
panic: runtime error: index out of range [0] with length 0

goroutine 1 [running]:
github.com/hashgraph/hedera-sdk-go/v2.(*_LockableSlice)._Get(...)
	C:/Users/jerem/go/pkg/mod/github.com/hashgraph/hedera-sdk-go/v2@v2.34.0/lockable_slice.go:66
github.com/hashgraph/hedera-sdk-go/v2.(*_LockableSlice)._GetCurrent(...)
	C:/Users/jerem/go/pkg/mod/github.com/hashgraph/hedera-sdk-go/v2@v2.34.0/lockable_slice.go:94
github.com/hashgraph/hedera-sdk-go/v2.(*executable).getNodeAccountID(0x7ff7fba08573?)
	C:/Users/jerem/go/pkg/mod/github.com/hashgraph/hedera-sdk-go/v2@v2.34.0/executable.go:191 +0xea
github.com/hashgraph/hedera-sdk-go/v2._Execute(0xc000237e60, {0x7ff7fc48ea28, 0xc000551ce0})
	C:/Users/jerem/go/pkg/mod/github.com/hashgraph/hedera-sdk-go/v2@v2.34.0/executable.go:228 +0x278
github.com/hashgraph/hedera-sdk-go/v2.(*AccountBalanceQuery).Execute(0xc000551ce0, 0xc000237e60)
	C:/Users/jerem/go/pkg/mod/github.com/hashgraph/hedera-sdk-go/v2@v2.34.0/account_balance_query.go:110 +0x136
main.main()
	C:/Workspace/hedera-go-examples/hedera-example.go:74 +0x10d8

Process finished with exit code 2
```

### Additional context

`C:/Workspace/hedera-go-examples/hedera-example.go:74` refers to the following line of code:
```
accountBalance, err := query.Execute(client)
```

Full code:
```
package main

import (
	"fmt"
	"os"

	"github.com/hashgraph/hedera-sdk-go/v2"
	"github.com/joho/godotenv"
)

func main() {

	//Loads the .env file and throws an error if it cannot load the variables from that file correctly
	err := godotenv.Load(".env")
	if err != nil {
		panic(fmt.Errorf("Unable to load environment variables from .env file. Error:\n%v\n", err))
	}

	//Grab your testnet account ID and private key from the .env file
	myAccountId, err := hedera.AccountIDFromString(os.Getenv("MY_ACCOUNT_ID"))
	if err != nil {
		panic(err)
	}

	myPrivateKey, err := hedera.PrivateKeyFromString(os.Getenv("MY_PRIVATE_KEY"))
	if err != nil {
		panic(err)
	}

	//Print your testnet account ID and private key to the console to make sure there was no error
	fmt.Printf("\nThe account ID is = %v\n", myAccountId)
	fmt.Printf("The private key is = %v", myPrivateKey)

	//Create your testnet client
	client := hedera.ClientForTestnet()
	client.SetOperator(myAccountId, myPrivateKey)

	// Set default max transaction fee & max query payment
	client.SetDefaultMaxTransactionFee(hedera.HbarFrom(100, hedera.HbarUnits.Hbar))
	client.SetDefaultMaxQueryPayment(hedera.HbarFrom(50, hedera.HbarUnits.Hbar))

	//Generate new keys for the account you will create
	newAccountPrivateKey, err := hedera.PrivateKeyGenerateEd25519()
	if err != nil {
		panic(err)
	}

	newAccountPublicKey := newAccountPrivateKey.PublicKey()

	//Create new account and assign the public key
	newAccount, err := hedera.NewAccountCreateTransaction().
		SetKey(newAccountPublicKey).
		SetInitialBalance(hedera.HbarFrom(1000, hedera.HbarUnits.Tinybar)).
		Execute(client)

	//Request the receipt of the transaction
	receipt, err := newAccount.GetReceipt(client)
	if err != nil {
		panic(err)
	}

	//Get the new account ID from the receipt
	newAccountId := *receipt.AccountID

	//Print the new account ID to the console
	fmt.Println("\n")
	fmt.Printf("New account ID: %v\n", newAccountId)

	//Create the account balance query
	query := hedera.NewAccountBalanceQuery().
		SetAccountID(newAccountId)

	//Sign with client operator private key and submit the query to a Hedera network
	accountBalance, err := query.Execute(client)
	if err != nil {
		panic(err)
	}

	//Print the balance of tinybars
	fmt.Println("New account balance for the new account is", accountBalance.Hbars.AsTinybar())
}
```

### Hedera network

testnet

### Version

v2.34.0

### Operating system

Windows

**Comment by gsstoykov** [comment]
Is this matter urgent for so we can take it into consideration for our releases?

**Comment by gsstoykov** [comment]
Problem should be eliminated try it out with the latest rel.
