### ISSUE TITLE
`TransferTransaction` fails with segmentation violation error

### ISSUE THREAD

**Issue by 0xivanov** [hashgraph/hedera-sdk-go#998]
### Description

``` bash
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x9b0d6e]

goroutine 14776 [running]:
github.com/hashgraph/hedera-sdk-go/v2.(*_ManagedNetwork)._ReadmitNodes(0xc0001a2f18)
        /go/pkg/mod/github.com/hashgraph/hedera-sdk-go/v2@v2.23.0/managed_network.go:136 +0x24e
github.com/hashgraph/hedera-sdk-go/v2.(*_ManagedNetwork)._GetNumberOfNodesForTransaction(0xc0001a2f18)
        /go/pkg/mod/github.com/hashgraph/hedera-sdk-go/v2@v2.23.0/managed_network.go:144 +0x25
github.com/hashgraph/hedera-sdk-go/v2.(*_Network)._GetNodeAccountIDsForExecute(0xc0001a2f18)
        /go/pkg/mod/github.com/hashgraph/hedera-sdk-go/v2@v2.23.0/network.go:151 +0x7a
github.com/hashgraph/hedera-sdk-go/v2._TransactionFreezeWith(0xc000553c00, 0xc0001a2f00, 0xc0003d2cb0)
        /go/pkg/mod/github.com/hashgraph/hedera-sdk-go/v2@v2.23.0/transaction.go:505 +0x78
github.com/hashgraph/hedera-sdk-go/v2.(*TransferTransaction).FreezeWith(0xc000553c00, 0xc0001a2f00)
```

### Steps to reproduce

-

### Hedera network

mainnet

### Version

2.40.0

### Operating system

None

**Comment by 0xivanov** [comment]
Fixed in https://github.com/hashgraph/hedera-sdk-go/pull/765
